package gwt.shared;

import java.io.Serializable;

/*
 * class Book includes information of each book
 * bookID is generated by Datastore
 * other info (bookName, type, color, age, gender, owner) are from user input
 * 
 */

public class Book implements Serializable {

	public String bookID;
	private String bookAuthor;
	private String bookTitle;
	private String bookType;
	private String bookPrice;
	private String bookPages;
	private String bookISBN;

	public Book() {

	}

	public Book(String author, String title, String type, String price, String pages, String ISBN) {
		this.bookAuthor = author;
		this.bookTitle = title;
		this.bookType = type;
		this.bookPrice = price;
		this.bookPages = pages;
		this.bookISBN = ISBN;

	}

	public Book(String author, String title, String type, String price, String pages, String ISBN, String keyString) {

		this.bookAuthor = author;
		this.bookPrice = price;
		this.bookPages = pages;
		this.bookISBN = ISBN;
		this.bookType = type;
		this.bookTitle = title;
		this.bookID = keyString;
	}

	public void setBookID(String bookID) {
		this.bookID = bookID;
	}

	public String getBookAuthor() {
		return this.bookAuthor;
	}

	public String getBookTitle() {
		return this.bookTitle;
	}

	public String getBookType() {
		return this.bookType;
	}

	public String getBookPrice() {
		return this.bookPrice;
	}

	public String getBookPages() {
		return this.bookPages;
	}

	public String getBookISBN() {
		return this.bookISBN;
	}

}
